### ISSUE TITLE
Application Crashes when Fetching meal.rating and saving into cell.ratingControl.rating

### ISSUE THREAD

**Issue by MzxzD** [MzxzD/FoodTracker#1]
In the MealTableViewController.swift, function tableView, when fetching the placeholder meals and gets ready to display, the following line:
cell.ratingControl.rating = meal.rating
makes the app terminate with following error:
Thread 1: EXC_BAD_ACCESS (code=2, address=0x10268a0f8)

**Comment by wideking** [comment]
@MzxzD Nažalost ovo mi nije puno pomoglo, ali bez brige uspio sam doći do problema :)
Povukao sam dolje projekt i pokrenio ga. Općenito ovaj opis: Thread 1: EXC_BAD_ACCESS (code=2, address=0x10268a0f8, ne govori puno.  EXC_BAD_ACCESS obično znači da ne može naći refrencu na objekt i sl. ali to to ne govori o kojoj referenci je riječ. Međutim, konzola češće nudi korisne informacije...
Srećom za nas, sada je konzola prazna i ima samo jednu stvar koju ispiše : 2018-05-09 18:16:11.305158+0200 FoodTracker[38240:2457855] Unknown class Mea in Interface Builder file.

Budući da mi je cilj naučiti te pecati, a ne te hraniti, neću ti reći točno gdje je problem :)) Pokušaj u xcode search-u Searchati "Mea". Naći će ti puno fileova. Obrati pažnju na drugi dio rečenice - "Interface Builder". Taj dio rečenice ti govori gdje je problem. Ja ću ti reći da se problem nalazi u Storyboardu.

Kada pofixaš, prije nego što zatvoriš ovaj issue odgovori mi na slijedeća pitanja: 
1. Što je Interface Builder, te št on radi?
2. Objasni kako sam zaključio da je problem u storyboard fileu?

**Comment by MzxzD** [comment]
@wideking OK. Riješio sam problem.
Očito sam, kako sam povezivao klasu sa Horizontal Stack Viewom, nisam previše pazio što pišem i mislio sam da će autocomplete napraviti svoje.

Što se pitanja tiće:
1. Interface Builder je "Drag & Drop" naćin postavljanja vizualnog dijela koda, što programeru omogućuje pravljenje UI-a bez previše programiranja samog UI-a. I to se radi na Storryboard-u

2. Odgovor na ovo pitanje je praktički povezan sa prvim, jer baš i piše "Unknown class Mea in Interface Builder file." A interface builder file je nama storryboard.

Nadam se da sam dobro odgovorio na Vaša pitanja

**Comment by wideking** [comment]
Bravo! Odlično si zaključio i odgovorio :)
